### ISSUE TITLE
Middle click emulation stopped working

### ISSUE THREAD

**Issue by goggle** [gaul/libinput-force-middle-click-emulation#1]
Hi,

Since today, this does not work anymore for me...
I'm using it on Arch Linux for several months now without any problem, but suddenly it stopped working.

Running the compiled `hook.so` directly gives:
```
fish: “./hook.so” terminated by signal SIGSEGV (Address boundary error)
```
I don't know if it used to give another output.

I will try to downgrade some packages to see if I can narrow down the cause of the problem.

**Comment by goggle** [comment]
I was able to narrow down the issue:
I have downgraded the Arch Linux packages `gnome-shell`, `mutter` and `gtk3` and now it works again!

So it works in this configuration:
```
gnome-shell-1:3.32.2-2
mutter-3.32.2+5+g13a1624c1-2
gtk3-3.24.7+19+g91f2ad4a2f-1
```

But it *does not* work in this configuration:
```
gnome-shell-1:3.32.2+1+g24cb1c1aa-1
mutter-3.32.2+5+g13a1624c1-2
gtk3-1:3.24.8+177+gae2ef1472c-1
```

Unfortunately, after downgrading Gnome keeps crashing constantly, so I will need to upgrade again. I will have a look at the changes in the packages to narrow down the issue even further.

**Comment by goggle** [comment]
Ok, so I just found out, that it is enough to downgrade `gnome-shell` from version `1:3.32.2+1+g24cb1c1aa-1` to `1:3.32.2-2`.

Here you can see the difference of package build instructions: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/gnome-shell&id=f9e6a448ae85ed3a840d36940c554d46606da27e
There are two differences:

1. It calls `setcap cap_sys_nice+ep usr/bin/gnome-shell` as a post-install instruction.
2. It uses another upstream commit to build the package. It is only one patch that gets applied, which can be seen here: https://gitlab.gnome.org/GNOME/gnome-shell/commit/24cb1c1aabe36b905ce009c2c786f4d70d6184d7

**Comment by gaul** [comment]
What is the stack trace from the SIGSEGV?

**Comment by goggle** [comment]
@gaul I think it is not relevant, because with the older version of `gnome-shell` it still gives that `SIGSEGV` when I try to run `hook.so` directly, but the emulated middle click works. I think `hook.so` is not meant to run directly anyway.

**Comment by goggle** [comment]
I have also reported the issue on the Arch Linux bug tracker: https://bugs.archlinux.org/task/62829?project=1&string=gnome-shell

**Comment by goggle** [comment]
I have just updated to Gnome 3.34 and unfortunately, it still does not work...
Is there now a native way to enable middle click emulation in Gnome?

**Comment by gaul** [comment]
My Fedora desktop still runs Gnome 3.32 so I cannot test this yet.  I have been trying to fix this in GNOME itself although only the first of two needed pull requests merged:

* https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/merge_requests/6
* https://gitlab.gnome.org/GNOME/mutter/merge_requests/256

I do not believe the first one should cause issues.  Do you have any other symptoms other than it doesn't work?

**Comment by goggle** [comment]
Thanks for your effort to bring this feature into Gnome! Too bad it didn't make it into 3.34. I hope there will still be a way to enable this.

> Do you have any other symptoms other than it doesn't work?

Unfortunately not... Is there a way to debug this? What can I try?

**Comment by gaul** [comment]
I tried upgrading my desktop to Fedora 31 to test with a newer GNOME but encountered a [kernel panic](https://bugzilla.redhat.com/show_bug.cgi?id=1752961).  I am afraid that I am blocked on this for now.

**Comment by goggle** [comment]
No problem. I'm not even sure if it is a Gnome-related problem or an Arch Linux related problem. It used to work fine until an update from gnome-shell `3.32.2` to a patched version of `3.32.2` like described in https://github.com/gaul/libinput-force-middle-click-emulation/issues/1#issuecomment-499484001. Since I recently updated to Gnome `3.34`, I am not able to keep that old package anymore...

If you know a distribution that already ships with Gnome 3.34, I could set up a virtual machine and test it there...
Or if you have an idea how to debug this issue, I would be happy to help.

**Comment by goggle** [comment]
I could finally debug the cause of this issue. It's an Arch Linux related issue: In https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/gnome-shell&id=f9e6a448ae85ed3a840d36940c554d46606da27e the following post-build script got introduced:
```
post_install() {
  setcap cap_sys_nice+ep usr/bin/gnome-shell
}

post_upgrade() {
  post_install
}
```
I have rebuild gnome-shell 3.34 without this, and now the middle-click emulation works again!

Does anybody know what this `setcap` command does and why it is needed? Maybe @heftig?

**Comment by gaul** [comment]
It looks like this should allow gnome-shell to set a different/higher priority without a full setuid.  I don't think this is related to this project so I will close this issue since you have a workaround.

**Comment by goggle** [comment]
Thank you @gaul for your effort. It would be great to get this feature into Gnome upstream.

**Comment by gaul** [comment]
Thanks, I'm trying...
