### ISSUE TITLE
Stopped working in Gnome 3.36.1

### ISSUE THREAD

**Issue by goggle** [gaul/libinput-force-middle-click-emulation#3]
Since I've found the workaround (issue #1) it really worked great for a long time.
But now it stopped working in gnome-shell 3.36.1 (it still worked with gnome-shell 3.36.0) even when the workaround is applied.
@gaul Do you know if something recently changed in Gnome, that prevents `libinput-middle-click-emulation` from working correctly?

**Comment by goggle** [comment]
I have just found a solution:

You can enable
```
org.gnome.desktop.peripherals.mouse.middle-click-emulation
```

It then works without `ibinput-middle-click-emulation`.
@gaul Does this mean that your changes are now officially part of Gnome?
That should probably be mentioned in the README.

**Comment by gaul** [comment]
[GNOME/mutter#256](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/256) finally merged so I believe this workaround is no longer necessary.  Could you add a blurb to the README including which commands are needed and what version of GNOME fixes this?
